language: cpp
dist: xenial
git:
  depth: 5
  quiet: true

python: 3.7



matrix:
  include:

    # todo
    # - name: osx
    #   os: osx
    #   osx_image: xcode11
    #   compiler: clang
    #   script:
    #    - mkdir build && cd build
    #    - cmake  ..
    #    - make

    - name: linux (clang)
      os: linux
      compiler: clang++
      script:
       - mkdir build && cd build
       - cmake  ..
       - make

    - name: linux (gcc)
      os: linux
      compiler: gcc
      script:
       - $CXX --version
       - mkdir build && cd build
       - cmake ..
       - make
    # todo
    # for windows boost is too old. Chocolatey is outdated
    # - name: windows
    #   os: windows



before_install:
    - source .travis_before_install.bash

install:
    - source .travis_install.bash
